[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
remappings = []
script = "script"
cache_path = "cache"
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 200
evm_version = "paris"
solc_version = "0.8.24"
via_ir = false
dotenv = ".env"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "preserve"
single_line_statement_blocks = "preserve"
ignore = ["src/console.sol", "src/console2.sol"]